version: 0.1
phases:
  install:
    commands:
      - npm install
      - echo *******; aws iam get-user; echo *******
  pre_build:
    commands:
      - npm test
  build:
    commands:
      - npm run package
artifacts:
  type: zip
  files:
    - serverless-output.yaml
